# Default arguments for train_function_encoder.py
encoder_type: input
dataset: fwi
model: nonlinear

n_basis: 100

hidden_sizes: [512, 512, 512]
regularization: 0.001

batch_size: 20
epochs: 20000
learning_rate: 0.0001

seed: 42

checkpoint_interval: 100
resume: true
