# Default arguments for train_model.py
dataset: burgers_1d
model: nonlinear
hidden_sizes: [256, 256, 256]
forward_model: b2b_nonlinear
lambda_u: 0.0

batch_size: 50
epochs: 10000
learning_rate: 0.0001

log_dir: /store/at46867/b2b_operator_inverse/

seed: 42

checkpoint_interval: 100
resume: false
