[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "b2b-operator-inverse"
version = "0.1.0"
description = "Inverse neural operator models and utilities."
authors = [
    { name = "Your Name", email = "your.email@example.com" }
]
requires-python = ">=3.8"
dependencies = [
    "numpy",
    "torch>=2.5,<2.6",
    "matplotlib",
    "scipy",
    "function-encoder @ git+https://github.com/ajthor/function-encoder.git@v1.2.0",
    "pyyaml",
    "safetensors",
    "datasets",
    "torch-tb-profiler",
    "scikit-image",
]

[tool.setuptools.packages.find]
where = ["."]
